"""fourth migration

Revision ID: f63d656b5055
Revises: a151b2c27953
Create Date: 2024-02-06 19:30:14.486757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f63d656b5055'
down_revision = 'a151b2c27953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charityproject', sa.Column('project_total_time', sa.Interval(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('charityproject', 'project_total_time')
    # ### end Alembic commands ###
